version: "3.8"

services:
  together_backend:
    restart: "no"
    build:
      context: .
      dockerfile: ./deployments/Dockerfile
    env_file:
      - .env.docker
    ports:
      - "8001:8001"
    command: /main
